version: "3.7"
services:
  # Override defaults so PostgreSQL is used as the database for this service.
  drupal:
    environment:
      DRUPAL_DEFAULT_DB_DRIVER: pgsql
      # Use the edge name so the Drush on the host machine can access it.
      DRUPAL_DEFAULT_DB_HOST: postgresql.${COMPOSE_PROJECT_NAME-isle-dc}.localhost
      DRUPAL_DEFAULT_DB_PORT: 5432