version: "3.7"
networks:
  default:
    internal: true
volumes:
  postgresql-data:
services:
  # This exists side by side with the 'database' service which is expected to be
  # MySQL type. This is because Matomo doesn't support PostgreSQL so if we adopt
  # it we still need to have a MySQL as well. Additionally the defaults need to 
  # change on services which use PostgreSQL for those there is 
  # docker-compose.SERVICE.postgresql.yml files which are included when the 
  # respective 'SERVICENAME_DATABASE_SERVICE' variable is set to 'postgresql'.
  postgresql:
    image: ${REPOSITORY:-islandora}/postgresql:${TAG:-latest}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
